Backport/1.6 rc (#97)
* PLAT-10318: Fix Invalid keystore format (#93)

Java bots were generated with the PEM certificates instead of the
truststore file.

Added tests checking that the truststore and PEMs file are similar.
Made the tests faster by generating smaller RSA keypairs.

Removed Snyk as we use the Github integration (these changes were
automatically made by a Bot)

(cherry picked from commit 1b285b6e7d3d6fc718077e1af50a59e7d8b2b1bb)

* PLAT-10347: Invalid RSA keys are sometimes generated (#95)

RSA keys created by the generator were sometimes not accepted by the
BDK, failing with the error message:
java.lang.IllegalArgumentException: failed to construct sequence from byte[]: corrupted stream detected

While no obvious problems were found in the RSA keys themselves (checking them
with openssl command as1nparse), tests showed that out of 100 RSA
private keys, 16 were failing.

Changing the keypair library to use node-forge instead seems to fix
the problem. Besides node-forge is much faster, already used elsewhere
in the generator and keypair is no really maintained.

A new keypair shared function has been introduced, to replace the
library out of the box, minimizing the diff.

(cherry picked from commit df137dd95fdbb39337c7d107a123baca45a74b91)

* PLAT-10388: Fix Python bot generator using signed certificate option (#96)

* SpringBoot bot generator

* Fix Python bot generator using signed certificate option

(cherry picked from commit f0c9d502ec170fcc7e0d1b2d55a109ca8f63a0f0)

* Bump version to 1.6.3

Co-authored-by: Youri Bonnaffé <63661676+symphony-youri@users.noreply.github.com>