PLAT-10347: Invalid RSA keys are sometimes generated
RSA keys created by the generator were sometimes not accepted by the
BDK, failing with the error message:
java.lang.IllegalArgumentException: failed to construct sequence from byte[]: corrupted stream detected

While no obvious problems were found in the RSA keys themselves (checking them
with openssl command as1nparse), tests showed that out of 100 RSA
private keys, 16 were failing.

Changing the keypair library to use node-forge instead seems to fix
the problem. Besides node-forge is much faster, already used elsewhere
in the generator and keypair is no really maintained.

A new keypair shared function has been introduced, to replace the
library out of the box, minimizing the diff.